*** Settings ***
Documentation    This file stores the default variables and values for the project


*** Variables ***
${BROWSER}        Chrome     # Chrome/Firefox/Edge
${DEFAULT_URL}    http://10.255.0.150:32022/

${LOGIN_USERNAME}    admin@microsoft.com
${LOGIN_PASSWORD}    Pass@word1

${EXCEL_PATH_1}    Lab-04/data/data1.xlsx
${EXCEL_PATH_2}    Lab-04/data/data2.xlsx
${SHEET_NAME}    Sheet1

